# Install Hermes Agent on Windows reference lab and smoke-test two modes:
#   1) Raw Ollama (always llama3.2:3b)
#   2) Lumen gateway (hybrid routing via :8080)
param(
    [string]$LabRoot = "D:\lumen-stream-lab",
    [switch]$InstallOnly,
    [switch]$SkipInstall,
    [switch]$GatewayOnly,
    [int]$GatewayPort = 8080,
    [int]$HermesTimeoutSec = 90
)

$ErrorActionPreference = "Stop"
. "$LabRoot\deploy\win-env-d.ps1"

function Write-Step($msg) {
    Write-Host ""
    Write-Host "=== $msg ===" -ForegroundColor Cyan
}

function Ensure-Ollama {
    Write-Step "Ollama"
    $tags = $null
    try {
        $tags = Invoke-RestMethod -Uri "http://127.0.0.1:11434/api/tags" -TimeoutSec 8
    } catch {
        Write-Host "Starting ollama serve ..." -ForegroundColor DarkGray
        Start-Process -FilePath "ollama" -ArgumentList "serve" -WindowStyle Hidden
        $deadline = (Get-Date).AddSeconds(30)
        while ((Get-Date) -lt $deadline) {
            Start-Sleep -Seconds 3
            try {
                $tags = Invoke-RestMethod -Uri "http://127.0.0.1:11434/api/tags" -TimeoutSec 8
                break
            } catch { }
        }
        if (-not $tags) { throw "Ollama did not start within 30s" }
    }
    $names = @($tags.models | ForEach-Object { $_.name })
    Write-Host "Ollama OK. Models: $($names.Count)"
    foreach ($need in @("llama3.2:3b", "llama3.2:1b", "lfm-balanced", "qwen2.5-3b-lumen")) {
        $found = $false
        foreach ($n in $names) {
            if ($n -eq $need -or $n -eq "$need`:latest" -or $n.StartsWith("$need`:")) { $found = $true; break }
        }
        if (-not $found) { Write-Host "WARN: missing model $need" -ForegroundColor Yellow }
    }
}

function Ensure-Hermes {
    if ($SkipInstall) { return }
    $hermes = Get-Command hermes -ErrorAction SilentlyContinue
    if ($hermes) {
        Write-Host "Hermes already installed: $($hermes.Source)" -ForegroundColor Green
        return
    }
    Write-Step "Installing Hermes Agent (may take 10-15 min)"
    $installUrl = "https://hermes-agent.nousresearch.com/install.ps1"
    $installScript = (Invoke-WebRequest -UseBasicParsing -Uri $installUrl).Content
    Invoke-Expression $installScript
    $hermes = Get-Command hermes -ErrorAction SilentlyContinue
    if (-not $hermes) {
        $bin = Join-Path $env:LOCALAPPDATA "hermes\bin\hermes.cmd"
        if (Test-Path $bin) {
            $env:PATH = "$(Split-Path $bin);$env:PATH"
            $hermes = Get-Command hermes -ErrorAction SilentlyContinue
        }
    }
    if (-not $hermes) {
        throw "Hermes install finished but hermes CLI not found. Open a new terminal and re-run."
    }
    Write-Host "Hermes: $($hermes.Source)" -ForegroundColor Green
}

function Ensure-HermesNative {
    Write-Step "hermes-ollama-native"
    python -m pip install -U hermes-ollama-native | Out-Null
    $env:HERMES_OLLAMA_NATIVE = "1"
    [Environment]::SetEnvironmentVariable("HERMES_OLLAMA_NATIVE", "1", "User")
}

function Write-HermesConfig {
    Write-Step "Hermes config (dual providers)"
    $hermesHome = if ($env:HERMES_HOME) { $env:HERMES_HOME } else { Join-Path $env:LOCALAPPDATA "hermes" }
    New-Item -ItemType Directory -Path $hermesHome -Force | Out-Null

    $cfg = @"
# Lumen reference lab - generated by win-install-and-test-hermes.ps1
model:
  default: llama3.2:3b
  provider: ollama-raw
  context_length: 8192

compression:
  enabled: false

providers:
  ollama-raw:
    base_url: http://127.0.0.1:11434/v1
    api_key: ollama
    default_model: llama3.2:3b
    api_mode: chat_completions
  lumen:
    base_url: http://127.0.0.1:$GatewayPort/v1
    api_key: lumen
    default_model: lumen-hybrid
    api_mode: chat_completions

agent:
  toolsets: []
"@
    $cfgPath = Join-Path $hermesHome "config.yaml"
    Set-Content -Path $cfgPath -Value $cfg -Encoding UTF8
    Write-Host "Wrote $cfgPath"
}

function Stop-GatewayOnPort {
    param([int]$Port)
    $lines = netstat -ano | Select-String ":$Port\s" | Select-String "LISTENING"
    foreach ($line in $lines) {
        $pid = ($line -split '\s+')[-1]
        if ($pid -match '^\d+$') {
            Write-Host "Stopping stale listener pid $pid on :$Port" -ForegroundColor DarkGray
            Stop-Process -Id ([int]$pid) -Force -ErrorAction SilentlyContinue
        }
    }
    Start-Sleep -Seconds 1
}

function Start-LumenGateway {
    param([int]$Port)
    Write-Step "Lumen gateway :$Port"
    $health = $null
    try {
        $health = Invoke-RestMethod -Uri "http://127.0.0.1:$Port/v1/health" -TimeoutSec 3
    } catch { }

    if ($health.ok) {
        Write-Host "Gateway already running on :$Port" -ForegroundColor Green
        return
    }

    Stop-GatewayOnPort -Port $Port
    Push-Location $LabRoot
    if (-not (Test-Path "hardware.json")) {
        python lumen.py probe | Out-Null
    }
    python -c "import lumen_router; print('lumen_router ok')" | Out-Null
    Pop-Location

    $resultsDir = Join-Path $LabRoot "results"
    New-Item -ItemType Directory -Path $resultsDir -Force | Out-Null
    $gwLog = Join-Path $resultsDir "gateway-hermes-test.log"
    $gwErr = Join-Path $resultsDir "gateway-hermes-test.err.log"

    # Redirect to files (not pipes) - pipe redirect can deadlock the gateway process.
    $proc = Start-Process -FilePath "python" `
        -ArgumentList "scripts\lumen_gateway.py --port $Port" `
        -WorkingDirectory $LabRoot `
        -WindowStyle Hidden `
        -RedirectStandardOutput $gwLog `
        -RedirectStandardError $gwErr `
        -PassThru

    $deadline = (Get-Date).AddSeconds(20)
    while ((Get-Date) -lt $deadline) {
        Start-Sleep -Seconds 2
        try {
            $health = Invoke-RestMethod -Uri "http://127.0.0.1:$Port/v1/health" -TimeoutSec 5
            if ($health.ok) {
                Write-Host "Gateway started (pid $($proc.Id))" -ForegroundColor Green
                return
            }
        } catch { }
        if ($proc.HasExited) { break }
    }

    $errTail = ""
    if (Test-Path $gwErr) { $errTail = (Get-Content $gwErr -Tail 15) -join "`n" }
    throw "Gateway failed on :$Port (exit=$($proc.ExitCode)). stderr tail:`n$errTail"
}

function Invoke-HermesQuery {
    param(
        [string]$Provider,
        [string]$Model,
        [string]$Prompt,
        [int]$TimeoutSec = 90
    )
    $bin = Join-Path $env:LOCALAPPDATA "hermes\bin"
    if (Test-Path $bin) { $env:PATH = "$bin;$env:PATH" }
    $env:HERMES_OLLAMA_NATIVE = "1"

    $hermesArgs = @("chat", "-q", $Prompt, "--provider", $Provider, "--model", $Model, "--no-markdown")
    Write-Host "hermes $($hermesArgs -join ' ') (timeout ${TimeoutSec}s)" -ForegroundColor DarkGray

    $job = Start-Job -ScriptBlock {
        param($ArgsList)
        $env:HERMES_OLLAMA_NATIVE = "1"
        $bin = Join-Path $env:LOCALAPPDATA "hermes\bin"
        if (Test-Path $bin) { $env:PATH = "$bin;$env:PATH" }
        $text = (& hermes @ArgsList 2>&1 | Out-String).Trim()
        return @{ exit = $LASTEXITCODE; output = $text }
    } -ArgumentList (,$hermesArgs)

    $done = Wait-Job $job -Timeout $TimeoutSec
    if (-not $done) {
        Stop-Job $job -Force | Out-Null
        Remove-Job $job -Force | Out-Null
        return @{ exit = 124; output = "TIMEOUT after ${TimeoutSec}s" }
    }
    $result = Receive-Job $job
    Remove-Job $job -Force | Out-Null
    return $result
}

function Test-LumenGatewayDirect {
    param([int]$Port, [string]$Prompt)
    $body = @{ messages = @(@{ role = "user"; content = $Prompt }) } | ConvertTo-Json -Depth 5
    $resp = Invoke-RestMethod -Uri "http://127.0.0.1:$Port/v1/chat/completions" `
        -Method Post -ContentType "application/json" -Body $body -TimeoutSec 180
    return $resp
}

# ---- main ----
Write-Step "Hermes + Lumen install and test"
Set-Location $LabRoot

Ensure-Ollama
Ensure-Hermes
Ensure-HermesNative
Write-HermesConfig

if ($InstallOnly) {
    Write-Host "InstallOnly - done." -ForegroundColor Green
    exit 0
}

Start-LumenGateway -Port $GatewayPort

Write-Step "Test A - Lumen gateway (curl)"
$gw = Test-LumenGatewayDirect -Port $GatewayPort -Prompt "What is 2+2?"
Write-Host "Routed model: $($gw.lumen_plan.model) tier=$($gw.lumen_plan.tier) reason=$($gw.lumen_plan.reason)"
Write-Host "Response: $($gw.choices[0].message.content.Substring(0, [Math]::Min(120, $gw.choices[0].message.content.Length)))"

$gw2 = Test-LumenGatewayDirect -Port $GatewayPort -Prompt "What is Lumen Stream Lab? Reply in one sentence."
Write-Host "Routed model: $($gw2.lumen_plan.model) tier=$($gw2.lumen_plan.tier)"

if ($GatewayOnly) {
    Write-Step "GatewayOnly - skipping Hermes chat tests"
    exit 0
}

Write-Step "Test B - Raw Hermes + Ollama (always 3B)"
$raw = Invoke-HermesQuery -Provider "ollama-raw" -Model "llama3.2:3b" -Prompt "Reply with one word: OK" -TimeoutSec $HermesTimeoutSec
Write-Host "exit=$($raw.exit)"
Write-Host $raw.output

Write-Step "Test C - Hermes + Lumen gateway (hybrid)"
$hyb = Invoke-HermesQuery -Provider "lumen" -Model "lumen-hybrid" -Prompt "What is 2+2? Reply briefly." -TimeoutSec $HermesTimeoutSec
Write-Host "exit=$($hyb.exit)"
Write-Host $hyb.output

Write-Step "Summary"
Write-Host @"
Raw Ollama provider : ollama-raw  -> http://127.0.0.1:11434/v1  (llama3.2:3b)
Lumen provider      : lumen       -> http://127.0.0.1:$GatewayPort/v1 (hybrid)

Interactive:
  hermes chat --provider ollama-raw --model llama3.2:3b
  hermes chat --provider lumen --model lumen-hybrid

Gateway (keep running):
  python scripts\lumen_gateway.py --port $GatewayPort
"@ -ForegroundColor Green
